/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

/* The newlib minor version number. */
#define _NEWLIB_MINOR__ 10

/* The newlib version in string format. */
#define _NEWLIB_VERSION "2.10.0"

/* The newlib major version number. */
#define _NEWLIB__ 2

/* The newlib patch level. */
#define __NEWLIB_PATCHLEVEL__ 0

